package ai.algo1.marketbasket.feature.ideas

data class Recipe(
    val id: String,
    val title: String,
    val description: String,
    val image: String,
    val time: String,
    val servings: Int,
    val difficulty: String,
    val ingredients: List<String>,
    val instructions: List<String>,
    val videoUrl: String,
    val creator: String,
)

data class RecipeVideo(val id: String, val uri: String, val recipe: Recipe)

data class VideoActionsState(
    val favorited: Boolean = false,
    val bookmarked: Boolean = false,
    val addedToList: Boolean = false,
)

private val recipeData: List<Recipe> = listOf(
    Recipe(
        id = "1",
        title = "Chimichurri Steak Bites with Garlic Mashed Potatoes",
        description = "Easy, delicious chimichurri steak bites that hit every time, served with creamy garlic mashed potatoes. The best sauce for steak that will leave you speechless.",
        image = "https://alexrioscooks.com/wp-content/uploads/2024/12/img_4547-1-500x500.jpg",
        time = "30 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "1 lb ribeye steak, cut into 1-inch cubes",
            "Brazilian steak seasoning",
            "2 lbs Yukon Gold potatoes (or russet potatoes)",
            "4 tbsp butter",
            "1/2 cup heavy cream",
            "4 cloves garlic, minced",
            "Walmart seasoning (as mentioned in video)",
            "Salt and pepper to taste",
            "2 tbsp olive oil for searing",
            "Chimichurri sauce for serving",
        ),
        instructions = listOf(
            "Cut ribeye steak into 1 by 1 inch cubes and season with Brazilian steak seasoning.",
            "Heat olive oil in a large skillet over high heat.",
            "Sear steak bites on all sides until desired doneness, about 2-3 minutes per side.",
            "For the mashed potatoes, peel and cube Yukon Gold potatoes.",
            "Boil potatoes for about 15 minutes or until fork tender.",
            "Drain potatoes and return to pot.",
            "Add butter, cream, garlic, and the seasoning found at Walmart.",
            "Give the mashed potatoes a good mix until creamy and well combined.",
            "Serve chimichurri steak bites alongside the garlic mashed potatoes.",
            "Drizzle chimichurri sauce over the steak bites for the ultimate flavor experience.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@foodwithbearhands_1752615885738.mp4",
        creator = "foodwithbearhands",
    ),
    Recipe(
        id = "2",
        title = "Juicy Soy Glazed Chicken",
        description = "Crispy-edged chicken with a sticky savory and perfectly caramelized soy glaze sauce that will have you thanking us later.",
        image = "https://i0.wp.com/smittenkitchen.com/wp-content/uploads/2021/05/soy-basted-chicken-scaled.jpg?fit=1200%2C800&ssl=1",
        time = "15 mins",
        servings = 2,
        difficulty = "Easy",
        ingredients = listOf(
            "2 chicken breasts",
            "3 cloves garlic, minced",
            "2 tbsp oyster sauce",
            "2 tbsp soy sauce",
            "2 tbsp honey",
            "1/4 cup cornstarch",
            "Salt and pepper to taste",
            "2 tbsp vegetable oil",
            "Cooked rice for serving",
        ),
        instructions = listOf(
            "In a bowl, add minced garlic, oyster sauce, soy sauce, and honey. Stir well together until combined.",
            "Season the chicken with salt and pepper on both sides.",
            "Coat the chicken with cornstarch on both sides, ensuring even coverage.",
            "Heat vegetable oil in a large pan over medium-high heat.",
            "Pan fry the chicken for about 4 minutes on each side until crispy and golden brown.",
            "Remove chicken from pan and set aside.",
            "In the same pan, pour in the sauce mixture and simmer for about 30 seconds.",
            "Add back the chicken and cook on high heat for 1 minute on each side.",
            "Once the chicken is fully coated in the thick savory sauce, remove it from the pan.",
            "Slice the chicken and serve with a bed of rice. Enjoy!",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@conniecooks_1752615805845.mp4",
        creator = "conniecooks",
    ),
    Recipe(
        id = "3",
        title = "Bang Bang Chicken",
        description = "Insanely good Bang Bang chicken with 500 calories and 45 grams of protein. A healthy, flavorful dish you could eat every day, made with quality ingredients like Chosen Foods avocado oil.",
        image = "https://www.allrecipes.com/thmb/2ln3v3pthr09-iJC0xZAyOww0o4=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/AR-273785-bang-bang-chicken-Beauty-4x3-1357db9a1f1049e5bbc18c345b83edd4.jpg",
        time = "25 mins",
        servings = 3,
        difficulty = "Medium",
        ingredients = listOf(
            "1 lb chicken breast, cut into bite-sized pieces",
            "2 tbsp Chosen Foods avocado oil",
            "Salt and pepper to taste",
            "Bang Bang sauce ingredients (see full breakdown in description)",
            "Fresh herbs for garnish",
            "Lemon wedges for serving",
            "Cooked rice or vegetables for serving",
        ),
        instructions = listOf(
            "Cut chicken breast into bite-sized pieces and season with salt and pepper.",
            "Heat Chosen Foods avocado oil in a large skillet over medium-high heat.",
            "Cook chicken pieces until golden brown and cooked through, about 5-7 minutes.",
            "Prepare the Bang Bang sauce according to the full breakdown in the description.",
            "Toss the cooked chicken with the Bang Bang sauce until well coated.",
            "Serve immediately with fresh herbs and lemon wedges.",
            "Pair with rice or vegetables for a complete meal.",
            "Enjoy this protein-packed dish that's perfect for weight loss and healthy eating.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@donaldo_cook_1752615906914.mp4",
        creator = "donaldo_cook",
    ),
    Recipe(
        id = "4",
        title = "Upside Down Chicken Caesar Salad",
        description = "A trendy twist on the classic Caesar salad with a crispy chicken cutlet on the bottom and fresh Caesar salad on top. Light, fresh, satisfying, and fun - the perfect summer staple.",
        image = "https://s23209.pcdn.co/wp-content/uploads/2023/01/220905_DD_Chx-Caesar-Salad_051-800x800.jpg",
        time = "25 mins",
        servings = 2,
        difficulty = "Easy",
        ingredients = listOf(
            "2 chicken cutlets",
            "1 cup breadcrumbs",
            "2 eggs, beaten",
            "1/4 cup all-purpose flour",
            "Salt and pepper to taste",
            "Vegetable oil for frying",
            "1 head romaine lettuce, chopped",
            "1/2 cup Greek yogurt",
            "2 tbsp lemon juice",
            "2 cloves garlic, minced",
            "1/4 cup parmesan cheese, grated",
            "2 tbsp olive oil",
            "1 tsp Dijon mustard",
            "Salt and pepper to taste",
            "Croutons for garnish",
        ),
        instructions = listOf(
            "Season chicken cutlets with salt and pepper on both sides.",
            "Set up breading station: flour in one bowl, beaten eggs in another, breadcrumbs in a third.",
            "Dredge chicken in flour, then dip in eggs, then coat with breadcrumbs.",
            "Heat vegetable oil in a large skillet over medium-high heat.",
            "Fry chicken cutlets until golden brown and crispy, about 3-4 minutes per side.",
            "Remove chicken and let drain on paper towels.",
            "In a small bowl, whisk together Greek yogurt, lemon juice, garlic, parmesan, olive oil, and Dijon mustard.",
            "Season dressing with salt and pepper to taste.",
            "Toss chopped romaine lettuce with the Greek yogurt Caesar dressing.",
            "Place crispy chicken cutlet on a plate and top with the dressed Caesar salad.",
            "Garnish with additional parmesan cheese and croutons.",
            "Serve immediately while chicken is still crispy and warm.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@munchinwithmaddie__1752615932632.mp4",
        creator = "munchinwithmaddie",
    ),
    Recipe(
        id = "5",
        title = "Hot Honey Ground Beef Bowls",
        description = "The viral recipe that's taking over the internet! These hot honey ground beef bowls are 10 out of 10 - an absolute powerhouse meal packed with protein, fiber, and healthy fats.",
        image = "https://feelgoodfoodie.net/wp-content/uploads/2025/05/Hot-Honey-Ground-Beef-Bowls-11.jpg",
        time = "40 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "2 large sweet potatoes, cubed",
            "1 lb ground beef",
            "2 tbsp tomato paste",
            "2 tbsp taco seasoning",
            "1/4 cup water",
            "1 cup cottage cheese",
            "2 ripe avocados, sliced",
            "Hot honey for drizzling",
            "Salt and pepper to taste",
            "1/2 tsp cinnamon",
            "Lettuce and tomatoes for garnish (optional)",
        ),
        instructions = listOf(
            "Preheat oven to 400°F (200°C). Line a baking sheet with parchment paper.",
            "Cube sweet potatoes and place on baking sheet. Season with salt, pepper, and cinnamon to bring out the sweetness.",
            "Bake sweet potatoes for 20-25 minutes, flipping halfway through and seasoning again.",
            "While sweet potatoes bake, prepare the ground beef in a large skillet over medium heat.",
            "Add tomato paste, taco seasoning, and a splash of water to the ground beef.",
            "Cook ground beef until browned and well-seasoned, breaking it up as it cooks.",
            "Remove sweet potatoes from oven when tender and golden brown.",
            "Build your bowls: start with sweet potatoes as the base.",
            "Add seasoned ground beef on top of the sweet potatoes.",
            "Add cottage cheese and sliced avocado to each bowl.",
            "Drizzle everything generously with hot honey.",
            "Optional: Add lettuce and tomatoes for extra volume and freshness.",
            "Serve immediately and enjoy this protein-packed, fiber-rich meal!",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@myproteinpantry_1752615954165.mp4",
        creator = "myproteinpantry",
    ),
    Recipe(
        id = "6",
        title = "Coconut Lime Cod Bowl",
        description = "A sensational one-pan weeknight dinner featuring coconut lime cod served with mango jalapeño salsa and white cabbage slaw. High protein, healthy, and absolutely banging!",
        image = "https://dishingouthealth.com/wp-content/uploads/2023/09/ThaiCoconutCod_Styled3.jpg",
        time = "30 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "4 cod fillets",
            "Cod marinade ingredients",
            "1 onion, finely chopped",
            "1 mango, diced",
            "2 jalapeños, finely chopped",
            "1/4 cup fresh coriander, chopped",
            "2 limes, juiced",
            "1/2 head white cabbage, shredded",
            "1/2 cup sour cream",
            "2 tbsp butter",
            "1 shallot, minced",
            "1 can coconut milk",
            "2 limes, zested and juiced",
            "Salt and pepper to taste",
        ),
        instructions = listOf(
            "Mix together your cod marinade ingredients in a bowl.",
            "Coat the cod fillets all over in the marinade sauce.",
            "Soak the chopped onion in water to reduce the powerful onion flavor.",
            "Mix the drained onion with mango, jalapeños, coriander, and lime juice to make the salsa.",
            "Prepare a simple white cabbage and sour cream slaw for the side.",
            "Melt butter in a large pan over medium-high heat.",
            "Sear the cod fillets until golden and cooked through, about 3-4 minutes per side.",
            "Remove cod from pan and set aside.",
            "In the same pan, sauté the minced shallot until softened.",
            "Make the coconut lime sauce by adding coconut milk, lime zest, and lime juice to the pan.",
            "Simmer the sauce until it becomes punchy, creamy, coconutty, and limey.",
            "Pour the coconut lime sauce over the cod fillets when serving.",
            "Serve the cod with the mango jalapeño salsa and white cabbage slaw on the side.",
            "Enjoy this light and fresh, high-protein weeknight dinner!",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@thegoodbite_1752615973369.mp4",
        creator = "thegoodbite",
    ),
    Recipe(
        id = "7",
        title = "Kachumbari (Kenyan Tomato Onion Salad)",
        description = "A refreshing and vibrant Kenyan salad made with fresh tomatoes, onions, and cilantro. This traditional dish is perfect as a side salad or condiment, offering a bright, tangy flavor.",
        image = "https://www.seriouseats.com/thmb/UOCM27z2_T4E0gexv3LUlbOuz6U=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20240808-SEA-KachumbariKenyanTomatoSalad-AmandaSuarez-05-44fa04a01f1943d5851ac3da2e801a7f.jpg",
        time = "20 mins",
        servings = 6,
        difficulty = "Easy",
        ingredients = listOf(
            "4 large ripe tomatoes, diced",
            "2 medium red onions, finely diced",
            "1/2 cup fresh cilantro, chopped",
            "2-3 fresh chili peppers (optional), finely chopped",
            "2 limes, juiced",
            "2 tbsp olive oil",
            "1 tsp salt",
            "1/2 tsp black pepper",
            "1/2 tsp ground cumin (optional)",
            "1/4 cup cucumber, diced (optional)",
            "1/4 cup bell pepper, diced (optional)",
        ),
        instructions = listOf(
            "Dice the tomatoes into small, uniform pieces and place in a large mixing bowl.",
            "Finely dice the red onions and add to the bowl with tomatoes.",
            "Chop fresh cilantro and add to the mixture.",
            "If using chili peppers, finely chop them and add to the salad.",
            "Squeeze fresh lime juice over the salad mixture.",
            "Drizzle olive oil over the ingredients.",
            "Season with salt, black pepper, and ground cumin if desired.",
            "Gently toss all ingredients together until well combined.",
            "Optional: Add diced cucumber and bell pepper for extra crunch and color.",
            "Let the salad sit for 10-15 minutes to allow flavors to meld.",
            "Taste and adjust seasoning with additional salt, lime juice, or chili as needed.",
            "Serve chilled as a side dish or condiment with grilled meats, rice, or bread.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@dr.vegan_1752616016179.mp4",
        creator = "dr.vegan",
    ),
    Recipe(
        id = "8",
        title = "Chickpea and Broccoli Stir-Fry Bowl",
        description = "A healthy and protein-packed vegetarian stir-fry featuring crispy chickpeas, tender broccoli, and a savory Asian-inspired sauce. This quick weeknight meal is loaded with nutrients.",
        image = "https://images.getrecipekit.com/20231026163702-chickpea.png?aspect_ratio=4:3&quality=90&",
        time = "25 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "2 cans (15 oz each) chickpeas, drained and rinsed",
            "1 large head broccoli, cut into florets",
            "2 tbsp olive oil",
            "3 cloves garlic, minced",
            "1 inch fresh ginger, grated",
            "2 tbsp soy sauce",
            "1 tbsp sesame oil",
            "1 tbsp rice vinegar",
            "1 tbsp honey or maple syrup",
            "1/2 tsp red pepper flakes",
            "2 cups cooked brown rice or quinoa",
            "2 green onions, sliced",
            "1/4 cup fresh cilantro, chopped",
            "1 tbsp sesame seeds",
            "Salt and pepper to taste",
            "Lime wedges for serving",
        ),
        instructions = listOf(
            "Heat 1 tbsp olive oil in a large wok or skillet over medium-high heat.",
            "Add drained chickpeas and cook for 5-7 minutes, stirring occasionally, until crispy and golden brown.",
            "Remove chickpeas from pan and set aside.",
            "In the same pan, add remaining olive oil and heat over medium-high heat.",
            "Add minced garlic and grated ginger, stir-fry for 30 seconds until fragrant.",
            "Add broccoli florets and stir-fry for 3-4 minutes until bright green and slightly tender.",
            "Return chickpeas to the pan with the broccoli.",
            "In a small bowl, whisk together soy sauce, sesame oil, rice vinegar, honey, and red pepper flakes.",
            "Pour the sauce over the chickpea and broccoli mixture.",
            "Stir-fry for 2-3 minutes until everything is well coated and heated through.",
            "Season with salt and pepper to taste.",
            "Divide cooked rice or quinoa among serving bowls.",
            "Top with the chickpea and broccoli stir-fry mixture.",
            "Garnish with sliced green onions, chopped cilantro, and sesame seeds.",
            "Serve immediately with lime wedges on the side.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@thenarddogcooks_1752616041042.mp4",
        creator = "thenarddogcooks",
    ),
    Recipe(
        id = "9",
        title = "30 Minute Tomato Garlic Rigatoni",
        description = "A viral recipe featuring juicy cherry tomatoes and eight garlic cloves for maximum flavor. Perfect for tomato season with a creamy sauce that's balanced with a touch of sugar to cut the natural acidity.",
        image = "https://majasrecipes.com/wp-content/uploads/2024/09/tomato-garlic-pasta-1.jpg",
        time = "30 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "1 lb rigatoni pasta",
            "8 cloves garlic, minced",
            "2 pints cherry tomatoes",
            "1/4 cup white wine",
            "1 tsp sugar",
            "1/2 cup heavy cream",
            "1/4 cup fresh parsley, chopped",
            "2 tbsp olive oil",
            "Salt and pepper to taste",
            "Parmesan cheese for serving (optional)",
        ),
        instructions = listOf(
            "Bring a large pot of salted water to boil and cook rigatoni according to package directions until al dente.",
            "While pasta cooks, heat olive oil in a large skillet over medium heat.",
            "Add minced garlic and sauté until fragrant, about 1-2 minutes.",
            "Add cherry tomatoes to the skillet and cook until they start to burst and release their juices.",
            "Pour in white wine to deglaze the bottom of the pan, scraping up any browned bits.",
            "Add sugar to balance the natural acidity of the tomatoes.",
            "Stir in heavy cream and let the sauce simmer and thicken for 3-4 minutes.",
            "Add freshly chopped parsley to the sauce.",
            "Drain the cooked rigatoni and add it to the skillet with the sauce.",
            "Toss everything together until pasta is well coated with the creamy tomato sauce.",
            "Season with salt and pepper to taste.",
            "Serve immediately with optional parmesan cheese on top.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@majasrecipes_1752616059722.mp4",
        creator = "majasrecipes",
    ),
    Recipe(
        id = "10",
        title = "Caramelized Onion and Garlic Spaghetti",
        description = "A simple yet incredibly flavorful pasta dish featuring slowly caramelized onions and roasted garlic. The sweet, deep flavors of the caramelized onions pair perfectly with the rich, nutty garlic for a comforting weeknight meal.",
        image = "https://assets.epicurious.com/photos/5cb8bce9b6addb519525d1b2/1:1/w_3782,h_3782,c_limit/Caramelized-Onion-Pasta-recipe-100419.jpg",
        time = "45 mins",
        servings = 4,
        difficulty = "Easy",
        ingredients = listOf(
            "1 lb spaghetti",
            "3 large yellow onions, thinly sliced",
            "8 cloves garlic, minced",
            "1/4 cup olive oil",
            "2 tbsp butter",
            "1/4 cup white wine",
            "1/2 cup pasta water",
            "1/4 cup fresh parsley, chopped",
            "1/2 cup parmesan cheese, grated",
            "Salt and pepper to taste",
            "Red pepper flakes (optional)",
            "Extra virgin olive oil for finishing",
        ),
        instructions = listOf(
            "Bring a large pot of salted water to boil for the spaghetti.",
            "In a large skillet, heat olive oil and butter over medium-low heat.",
            "Add thinly sliced onions and cook slowly, stirring occasionally, until deeply caramelized (about 25-30 minutes).",
            "Add minced garlic to the caramelized onions and cook for 2-3 minutes until fragrant.",
            "Pour in white wine to deglaze the pan and scrape up any browned bits.",
            "Cook pasta according to package directions until al dente, reserving 1/2 cup of pasta water.",
            "Add pasta water to the onion and garlic mixture to create a silky sauce.",
            "Drain the spaghetti and add it to the skillet with the caramelized onions.",
            "Toss everything together until pasta is well coated with the sauce.",
            "Stir in chopped parsley and grated parmesan cheese.",
            "Season with salt, pepper, and red pepper flakes if desired.",
            "Drizzle with extra virgin olive oil before serving.",
            "Serve immediately with additional parmesan cheese on top.",
        ),
        videoUrl = "https://raw.githubusercontent.com/fawadalgo1/shopper-prototype/main/assets/recipe-videos/ssstik.io_@recipeincaption_1752616083617.mp4",
        creator = "recipeincaption",
    ),
)

val recipeVideos: List<RecipeVideo> = recipeData.map { recipe ->
    RecipeVideo(id = recipe.id, uri = recipe.videoUrl, recipe = recipe)
}
