package ai.algo1.marketbasket.core.domain.catalog

/** 1:1 transcription of src/services/categoryMaps.ts. */
object CategoryMaps {
    val KNOWN_CATEGORY_IDS: List<String> = listOf(
        "produce",
        "snacks",
        "dairy",
        "bakery",
        "beverages",
        "frozen",
    )

    val CATEGORY_STRING_MAP: Map<String, String> = mapOf(
        // ── beverages ──────────────────────────────────────────────────────────────
        "drinks" to "beverages",
        "fizzy drinks" to "beverages",
        "fizzy-drinks" to "beverages",
        "soft drinks" to "beverages",
        "soft-drinks" to "beverages",
        "carbonated drinks" to "beverages",
        "cola" to "beverages",
        "colas" to "beverages",
        "juice" to "beverages",
        "juices" to "beverages",
        "juice drinks" to "beverages",
        "juices & smoothies" to "beverages",
        "juices and smoothies" to "beverages",
        "smoothies" to "beverages",
        "water" to "beverages",
        "still water" to "beverages",
        "sparkling water" to "beverages",
        "flavoured water" to "beverages",
        "beer" to "beverages",
        "beer & cider" to "beverages",
        "beer and cider" to "beverages",
        "cider" to "beverages",
        "lager" to "beverages",
        "ales & stouts" to "beverages",
        "wine" to "beverages",
        "red wine" to "beverages",
        "white wine" to "beverages",
        "rose wine" to "beverages",
        "rosé wine" to "beverages",
        "champagne & sparkling" to "beverages",
        "champagne and sparkling" to "beverages",
        "prosecco" to "beverages",
        "spirits" to "beverages",
        "gin" to "beverages",
        "vodka" to "beverages",
        "whisky" to "beverages",
        "rum" to "beverages",
        "hot drinks" to "beverages",
        "coffee" to "beverages",
        "tea" to "beverages",
        "herbal tea" to "beverages",
        "tea & coffee" to "beverages",
        "energy drinks" to "beverages",
        "sports drinks" to "beverages",
        "squash" to "beverages",
        "squash & cordials" to "beverages",
        "squash and cordials" to "beverages",
        "mixers" to "beverages",
        "mixers & soft drinks" to "beverages",
        "bigger multipacks" to "beverages",
        "multipack cans" to "beverages",
        "multipacks" to "beverages",

        // ── bakery ─────────────────────────────────────────────────────────────────
        "bakery" to "bakery",
        "bread" to "bakery",
        "bread & wraps" to "bakery",
        "bread and wraps" to "bakery",
        "wraps & flatbreads" to "bakery",
        "rolls & baps" to "bakery",
        "morning goods" to "bakery",
        "croissants & pastries" to "bakery",
        "cakes" to "bakery",
        "cake" to "bakery",
        "cake & sweet mixes" to "bakery",
        "baking & dessert mixes" to "bakery",
        "home baking" to "bakery",
        "sugar & home baking" to "bakery",
        "sugar and home baking" to "bakery",
        "flour" to "bakery",
        "baking ingredients" to "bakery",
        "biscuits" to "bakery",
        "biscuits & crackers" to "bakery",
        "biscuits and crackers" to "bakery",
        "cookies" to "bakery",
        "pastry" to "bakery",
        "desserts" to "bakery",
        "puddings" to "bakery",
        "doughnuts" to "bakery",
        "muffins" to "bakery",
        "scones" to "bakery",

        // ── produce ────────────────────────────────────────────────────────────────
        "fruit & veg" to "produce",
        "fruit and veg" to "produce",
        "fresh fruit" to "produce",
        "fruit" to "produce",
        "vegetables" to "produce",
        "fresh vegetables" to "produce",
        "salad" to "produce",
        "salads" to "produce",
        "salad & herbs" to "produce",
        "herbs" to "produce",
        "fresh herbs" to "produce",
        "mushrooms" to "produce",
        "potatoes" to "produce",
        "root vegetables" to "produce",
        "leafy & brassicas" to "produce",
        "organic fruit & veg" to "produce",
        "exotic fruit" to "produce",
        "citrus fruit" to "produce",
        "berries" to "produce",
        "stir fry" to "produce",

        // ── dairy ──────────────────────────────────────────────────────────────────
        "dairy" to "dairy",
        "dairy & eggs" to "dairy",
        "dairy and eggs" to "dairy",
        "dairy, eggs & chilled" to "dairy",
        "eggs" to "dairy",
        "free range eggs" to "dairy",
        "cheese" to "dairy",
        "hard cheese" to "dairy",
        "soft cheese" to "dairy",
        "sliced cheese" to "dairy",
        "butter" to "dairy",
        "butter & spreads" to "dairy",
        "spreads" to "dairy",
        "margarine" to "dairy",
        "yoghurt" to "dairy",
        "yogurt" to "dairy",
        "greek yoghurt" to "dairy",
        "milk" to "dairy",
        "fresh milk" to "dairy",
        "plant-based milk" to "dairy",
        "oat milk" to "dairy",
        "cream" to "dairy",
        "crème fraîche" to "dairy",
        "creme fraiche" to "dairy",
        "custard" to "dairy",

        // ── snacks ─────────────────────────────────────────────────────────────────
        "snacks" to "snacks",
        "crisps" to "snacks",
        "crisps & snacks" to "snacks",
        "crisps and snacks" to "snacks",
        "popcorn" to "snacks",
        "nuts & seeds" to "snacks",
        "nuts and seeds" to "snacks",
        "chocolate" to "snacks",
        "chocolate bars" to "snacks",
        "sweets" to "snacks",
        "sweets & chocolate" to "snacks",
        "sweets and chocolate" to "snacks",
        "confectionery" to "snacks",
        "food cupboard" to "snacks",
        "tinned food" to "snacks",
        "canned food" to "snacks",
        "pasta" to "snacks",
        "pasta, rice & noodles" to "snacks",
        "rice" to "snacks",
        "noodles" to "snacks",
        "breakfast cereals" to "snacks",
        "cereal" to "snacks",
        "porridge & oats" to "snacks",
        "cereal bars" to "snacks",
        "cooking sauces" to "snacks",
        "condiments" to "snacks",
        "jams & spreads" to "snacks",
        "honey" to "snacks",
        "snacking" to "snacks",
        "dips" to "snacks",
        "crackers" to "snacks",
        "rice cakes" to "snacks",

        // ── frozen ─────────────────────────────────────────────────────────────────
        "frozen" to "frozen",
        "frozen food" to "frozen",
        "frozen foods" to "frozen",
        "frozen ready meals" to "frozen",
        "frozen meat" to "frozen",
        "frozen fish" to "frozen",
        "frozen meat & fish" to "frozen",
        "frozen meat and fish" to "frozen",
        "frozen chips & sides" to "frozen",
        "frozen chips and sides" to "frozen",
        "frozen chips" to "frozen",
        "frozen pizza" to "frozen",
        "frozen fruit & veg" to "frozen",
        "frozen fruit and veg" to "frozen",
        "ice cream" to "frozen",
        "ice cream & lollies" to "frozen",
        "ice cream and lollies" to "frozen",
        "lollies" to "frozen",
        "sorbet" to "frozen",
        "frozen desserts" to "frozen",
        "frozen pastry" to "frozen",
    )

    val CATEGORY_KEYWORDS: Map<String, List<String>> = mapOf(
        "produce" to listOf(
            "fruit", "vegetable", "grape", "apple", "banana", "orange", "tomato",
            "lettuce", "carrot", "onion", "potato", "berry", "melon", "lemon",
            "lime", "salad", "herb", "mushroom", "pepper", "cucumber", "spinach",
            "broccoli", "avocado", "mango", "pear", "peach", "plum", "cherry",
            "strawberry", "blueberry", "raspberry", "garlic", "ginger",
            "courgette", "zucchini", "aubergine", "eggplant", "leek", "radish",
        ),
        "dairy" to listOf(
            "milk", "cheese", "yogurt", "yoghurt", "butter", "cream", "egg", "eggs",
            "cheddar", "mozzarella", "parmesan", "brie", "feta", "ricotta",
            "cottage", "whipping", "sour cream",
        ),
        "bakery" to listOf(
            "bread", "cake", "pastry", "muffin", "croissant", "biscuit", "cookie",
            "roll", "bun", "loaf", "bagel", "sourdough", "brioche", "waffle",
            "pancake", "scone", "doughnut", "donut", "pie", "tart",
        ),
        "snacks" to listOf(
            "chip", "chips", "crisp", "crisps", "popcorn", "pretzel", "chocolate", "candy", "sweet",
            "snack", "granola bar", "protein bar", "cracker", "rice cake",
        ),
        "beverages" to listOf(
            "water", "juice", "soda", "coffee", "tea", "cold brew", "beer", "wine", "spirit",
            "coke", "cola", "pepsi", "fanta", "sprite", "7up", "lemonade",
            "smoothie", "kombucha", "sparkling", "energy drink", "squash",
            "milkshake", "cordial", "mixer",
        ),
        "frozen" to listOf(
            "frozen", "pizza", "gyoza", "dumpling", "dumplings", "ice cream", "gelato", "sorbet", "popsicle",
        ),
        "meat" to listOf(
            "meat", "steak", "sirloin", "pork", "chicken", "turkey", "ham", "bacon",
            "sausage", "beef", "burger", "frank", "franks", "ribs", "meatloaf",
        ),
        "seafood" to listOf(
            "seafood", "salmon", "shrimp", "clam", "clams", "crab", "scallop",
            "scallops", "cod", "tilapia", "trout", "perch", "oyster", "oysters",
        ),
    )
}
